// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy18LAWWEvmHsfOIlBSDKUCxPCpCTnDh4',
    appId: '1:161572956218:web:82d1f45c835afa96afed03',
    messagingSenderId: '161572956218',
    projectId: 'fcm-test253641',
    authDomain: 'fcm-test253641.firebaseapp.com',
    storageBucket: 'fcm-test253641.firebasestorage.app',
    measurementId: 'G-C3E17H19ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARBSMPiHcgmCBqk7bhtFh2gQO3RKdpnCk',
    appId: '1:161572956218:android:f7dde7a0f30a07b7afed03',
    messagingSenderId: '161572956218',
    projectId: 'fcm-test253641',
    storageBucket: 'fcm-test253641.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMkUCsL1A4Mb_npyBH59d5E67aD-HUm5A',
    appId: '1:161572956218:ios:8b593fa8e3ed332dafed03',
    messagingSenderId: '161572956218',
    projectId: 'fcm-test253641',
    storageBucket: 'fcm-test253641.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMkUCsL1A4Mb_npyBH59d5E67aD-HUm5A',
    appId: '1:161572956218:ios:8b593fa8e3ed332dafed03',
    messagingSenderId: '161572956218',
    projectId: 'fcm-test253641',
    storageBucket: 'fcm-test253641.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy18LAWWEvmHsfOIlBSDKUCxPCpCTnDh4',
    appId: '1:161572956218:web:ee992adcbedf3900afed03',
    messagingSenderId: '161572956218',
    projectId: 'fcm-test253641',
    authDomain: 'fcm-test253641.firebaseapp.com',
    storageBucket: 'fcm-test253641.firebasestorage.app',
    measurementId: 'G-QML8L7916C',
  );
}
